use_frameworks!

platform :ios, '8.0'

target 'SKinConfigManager_Example' do
  pod 'SKinConfigManager', :path => '../'

  target 'SKinConfigManager_Tests' do
    inherit! :search_paths

    
  end
end
